FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server=1:8.9p1-3ubuntu0.1 \
    pwgen=2.08-2build1 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    git=1:2.34.1-1ubuntu1.9 \
    wget=1.21.2-2ubuntu1 \
    xvfb=2:21.1.4-2ubuntu1.7~22.04.1 \
    devscripts=2.22.1ubuntu1 \
    libgtk-3-0=3.24.33-1ubuntu2 \
    libdbus-glib-1-2=0.112-2build1 \
    libasound2=1.2.6.1-1ubuntu1\
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/sshd \
    && sed -i '/PermitRootLogin prohibit-password/c\PermitRootLogin yes' /etc/ssh/sshd_config

RUN wget -O firefox-setup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64" \
    && tar -xvjf firefox-setup.tar.bz2 \
    && ln -s /usr/local/firefox/firefox /usr/bin/firefox \
    && wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux32.tar.gz \
    && tar -xvzf geckodriver* \
    && cp geckodriver /usr/bin/geckodriver

RUN git clone --depth=1 https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP/

ADD requirements_test.txt start_sshd.sh ./
RUN pip3 install -r requirements_test.txt

COPY tests tests

ENTRYPOINT ["python3", "-m", "http.server", "3000"]
