FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server=1:8.9p1-3ubuntu0.1 \
    pwgen=2.08-2build1 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    python3=3.10.6-1~22.04 \
    git=1:2.34.1-1ubuntu1.9 \
    patch=2.7.6-7build2 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/sshd \
    && sed -i '/PermitRootLogin prohibit-password/c\PermitRootLogin yes' /etc/ssh/sshd_config

RUN git clone --depth=1 https://github.com/moevm/devops-examples.git
WORKDIR /devops-examples/EXAMPLE_APP/

COPY requirements.txt add_host.patch start_sshd.sh ./
RUN pip3 install -r requirements.txt \
    && patch main.py add_host.patch

ENTRYPOINT ["python3", "main.py"]
